import type { Metadata } from 'next';
import React from 'react';

// styles
import '@/assets/styles/scss/index.scss';
import Header from '@/components/Header';
import PromoBanner from '@/components/PromoBanner';

// eslint-disable-next-line import/order

// metadata
export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_TITLE,
  description: 'Generated by create next app',
  icons: '/images/logo.png',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html>
      <body>
        <PromoBanner
          title="FRESH BEGINNINGS SALE:"
          discount="Extra 25% OFF"
          message="Limited Spots - start your journey today!"
          icon="🚀"
        />
        <Header />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
